name: Maven Build

on:
  push:
    branches:
      - '**' # Triggers on pushes to all branches

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21' 
          distribution: 'temurin'

      # Cache Maven dependencies for faster builds
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Run Maven command
      - name: Build with Maven
        run: mvn clean install -T 4
